### ISSUE TITLE
Number of posts on front page should be limited

### ISSUE THREAD

**Issue by alexdmiller** [djmailhot/BeatTide#59] opened 2012-02-26 06:09 UTC
Description:
The front page should not display an unlimited number of your posts / feed posts

Steps to reproduce:
Login to BeatTide
Subscribe to many users
See really long feed

Expected behavior:
There should be 10 or so posts displayed in each section on the front page. The posts could possibly be paginated, so the user can browse to the next 10 songs. This could potentially be done with ajax.

Actual behavior:
No limit to number of posts. Every single post of a user you have subscribed to is displayed on the front page.

**Comment by mwinstanley** [comment] 2012-02-26 06:12
Duplicate of https://github.com/djmailhot/BeatTide/issues/49

**Closed as completed by mwinstanley** 2012-02-26 06:12 UTC
Labels: Priority: MED, Bug
